ingress-nginx:
  controller:
    name: controller
    enableAnnotationValidations: true
  
    config:
      annotations-risk-level: Critical
  
    image:
      ## Keep false as default for now!
      chroot: false
      # registry: registry.k8s.io
      image: ingress-nginx/controller
      ## for backwards compatibility consider setting the full image url via the repository value below
      ## use *either* current default registry/image or repository format or installing chart by providing the values.yaml will fail
      ## repository:
      tag: "v1.13.2"
      digest: sha256:1f7eaeb01933e719c8a9f4acd8181e555e582330c7d50f24484fb64d2ba9b2ef
      digestChroot: sha256:2beb2139c53d6bcb9c8b11d68b412a6a1aa1de3a7e6040695848b0ce997b2be8
      pullPolicy: IfNotPresent
      runAsNonRoot: true
      # -- This value must not be changed using the official image.
      # uid=101(www-data) gid=82(www-data) groups=82(www-data)
      runAsUser: 101
      # -- This value must not be changed using the official image.
      # uid=101(www-data) gid=82(www-data) groups=82(www-data)
      runAsGroup: 82
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      readOnlyRootFilesystem: false
    # -- Configures the controller container name
    containerName: controller
    # -- Configures the ports that the nginx-controller listens on
    containerPort:
      http: 80
      https: 443
  
    # Global snippets in ConfigMap are still respected
    allowSnippetAnnotations: true
    # -- Required for use with CNI based kubernetes installations (such as ones set up by kubeadm),
    # since CNI and hostport don't mix yet. Can be deprecated once https://github.com/kubernetes/kubernetes/issues/23920
    # is merged
    hostNetwork: false
    ## Use host ports 80 and 443
    ## Disabled by default
    hostPort:
      # -- Enable 'hostPort' or not
      enabled: false
      ports:
        # -- 'hostPort' http port
        http: 80
        # -- 'hostPort' https port
        https: 443
    # NetworkPolicy for controller component.
    networkPolicy:
      # -- Enable 'networkPolicy' or not
      enabled: false
    # -- Election ID to use for status update, by default it uses the controller name combined with a suffix of 'leader'
    electionID: ""
    # -- This section refers to the creation of the IngressClass resource.
    # IngressClasses are immutable and cannot be changed after creation.
    # We do not support namespaced IngressClasses, yet, so a ClusterRole and a ClusterRoleBinding is required.
    ingressClassResource:
      # -- Name of the IngressClass
      name: nginx
      # -- Create the IngressClass or not
      enabled: true
      # -- If true, Ingresses without `ingressClassName` get assigned to this IngressClass on creation.
      # Ingress creation gets rejected if there are multiple default IngressClasses.
      # Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
      default: false
      # -- Annotations to be added to the IngressClass resource.
      controllerValue: k8s.io/ingress-nginx
    # -- For backwards compatibility with ingress.class annotation, use ingressClass.
    # Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation
    ingressClass: nginx
    publishService:
      # -- Enable 'publishService' or not
      enabled: true
      # -- Allows overriding of the publish service to bind to
      # Must be <namespace>/<service_name>
      pathOverride: ""
    # -- Allows customization of the configmap / nginx-configmap namespace; defaults to $(POD_NAMESPACE)
    configMapNamespace: ""
    tcp:
      # -- Allows customization of the tcp-services-configmap; defaults to $(POD_NAMESPACE)
      configMapNamespace: ""
  
    udp:
      # -- Allows customization of the udp-services-configmap; defaults to $(POD_NAMESPACE)
      configMapNamespace: ""
    ## https://blog.maxmind.com/2019/12/significant-changes-to-accessing-and-using-geolite2-databases/
    maxmindLicenseKey: ""
    # -- Additional command line arguments to pass to Ingress-Nginx Controller
    # E.g. to specify the default SSL certificate you can use
    # -- Use a `DaemonSet` or `Deployment`
  
    kind: Deployment
    # -- Annotations to be added to the controller Deployment or DaemonSet
  
    livenessProbe:
      httpGet:
        # should match container.healthCheckPath
        path: "/healthz"
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      httpGet:
        # should match container.healthCheckPath
        path: "/healthz"
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    # -- Path of the health check endpoint. All requests received on the port defined by
    # the healthz-port parameter are forwarded internally to this path.
    healthCheckPath: "/healthz"
    replicaCount: 1
    minAvailable: 1
    # -- Maximum unavailable pods set in PodDisruptionBudget. If set, 'minAvailable' is ignored.
    # maxUnavailable: 1
    # -- Eviction policy for unhealthy pods guarded by PodDisruptionBudget.
    # Ref: https://kubernetes.io/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/
    unhealthyPodEvictionPolicy: ""
    ## Define requests resources to avoid probe issues due to CPU utilization in busy nodes
    ## ref: https://github.com/kubernetes/ingress-nginx/issues/4735#issuecomment-551204903
    ## Ideally, there should be no limits.
    ## https://engineering.indeedblog.com/blog/2019/12/cpu-throttling-regression-fix/
    resources:
      ##  limits:
      ##    cpu: 100m
      ##    memory: 90Mi
      requests:
        cpu: 100m
        memory: 90Mi
    ## ref: https://github.com/microsoft/mimalloc
    ##
    enableMimalloc: true
    ## Override NGINX template
    customTemplate:
      configMapName: ""
      configMapKey: ""
    service:
      # -- Enable controller services or not. This does not influence the creation of either the admission webhook or the metrics service.
      enabled: true
      external:
        # -- Enable the external controller service or not. Useful for internal-only deployments.
        enabled: true
        # -- Labels to be added to the external controller service.
      # -- Type of the external controller service.
      # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
      type: LoadBalancer
      # -- Traffic distribution policy of the external controller service. Set to "PreferClose" to route traffic to endpoints that are topologically closer to the client.
      # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution
      trafficDistribution: ""
      # -- Represents the dual-stack capabilities of the external controller service. Possible values are SingleStack, PreferDualStack or RequireDualStack.
      # Fields `ipFamilies` and `clusterIP` depend on the value of this field.
      # Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
      ipFamilyPolicy: SingleStack
      # -- List of IP families (e.g. IPv4, IPv6) assigned to the external controller service. This field is usually assigned automatically based on cluster configuration and the `ipFamilyPolicy` field.
      # Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
      ipFamilies:
        - IPv4
      # -- Enable the HTTP listener on both controller services or not.
      enableHttp: true
      # -- Enable the HTTPS listener on both controller services or not.
      enableHttps: true
      ports:
        # -- Port the external HTTP listener is published with.
        http: 80
        # -- Port the external HTTPS listener is published with.
        https: 443
      targetPorts:
        # -- Port of the ingress controller the external HTTP listener is mapped to.
        http: http
        # -- Port of the ingress controller the external HTTPS listener is mapped to.
        https: https
      # -- Declare the app protocol of the external HTTP and HTTPS listeners or not. Supersedes provider-specific annotations for declaring the backend protocol.
      # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol
      appProtocol: true
      nodePorts:
        # -- Node port allocated for the external HTTP listener. If left empty, the service controller allocates one from the configured node port range.
        http: ""
        # -- Node port allocated for the external HTTPS listener. If left empty, the service controller allocates one from the configured node port range.
        https: ""
        # -- Node port mapping for external TCP listeners. If left empty, the service controller allocates them from the configured node port range.
        # Example:
        # tcp:
        #   8080: 30080
        tcp: {}
        # -- Node port mapping for external UDP listeners. If left empty, the service controller allocates them from the configured node port range.
        # Example:
        # udp:
        #   53: 30053
        udp: {}
  
  
    admissionWebhooks:
      name: admission
  
      enabled: true
      failurePolicy: Fail
      # timeoutSeconds: 10
      port: 8443
      certificate: "/usr/local/certificates/cert"
      key: "/usr/local/certificates/key"
      service:
        servicePort: 443
        type: ClusterIP
      createSecretJob:
        name: create
        # -- Deadline in seconds for the job to complete. Must be greater than 0 to enforce. If unset or 0, no deadline is enforced.
        activeDeadlineSeconds: 0
        # -- Security context for secret creation containers
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
      patchWebhookJob:
        name: patch
        # -- Deadline in seconds for the job to complete. Must be greater than 0 to enforce. If unset or 0, no deadline is enforced.
        activeDeadlineSeconds: 0
        # -- Security context for webhook patch containers
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        resources: {}
      patch:
        enabled: true
        image:
          # registry: registry.k8s.io
          image: ingress-nginx/kube-webhook-certgen
          ## for backwards compatibility consider setting the full image url via the repository value below
          ## use *either* current default registry/image or repository format or installing chart by providing the values.yaml will fail
          ## repository:
          tag: v1.6.2
          digest: sha256:050a34002d5bb4966849c880c56c91f5320372564245733b33d4b3461b4dbd24
          pullPolicy: IfNotPresent
        networkPolicy:
          # -- Enable 'networkPolicy' or not
          enabled: false
        nodeSelector:
          kubernetes.io/os: linux
        rbac:
          # -- Create RBAC or not
          create: true
        # -- Admission webhook patch job service account
        serviceAccount:
          # -- Create a service account or not
          create: true
          # -- Custom service account name
          name: ""
          # -- Auto-mount service account token or not
          automountServiceAccountToken: true
  
    metrics:
      port: 10254
      portName: metrics
      # if this port is changed, change healthz-port: in extraArgs: accordingly
      enabled: false
      service:
        # -- Enable the metrics service or not.
        enabled: true
  
      serviceMonitor:
        enabled: false
  
      prometheusRule:
        enabled: false
  
    lifecycle:
      preStop:
        exec:
          command:
            - /wait-shutdown
    priorityClassName: ""
  # -- Rollback limit
  ##
  revisionHistoryLimit: 10
  ## Default 404 backend
  ##
  defaultBackend:
    ##
    enabled: false
    name: defaultbackend
    image:
      # registry: registry.k8s.io
      image: defaultbackend-amd64
      ## for backwards compatibility consider setting the full image url via the repository value below
      ## use *either* current default registry/image or repository format or installing chart by providing the values.yaml will fail
      ## repository:
      tag: "1.5"
      pullPolicy: IfNotPresent
      runAsNonRoot: true
      # nobody user -> uid 65534
      runAsUser: 65534
      runAsGroup: 65534
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      readOnlyRootFilesystem: true
    extraArgs: {}
    serviceAccount:
      create: true
      name: ""
      automountServiceAccountToken: true
    # -- Additional environment variables to set for defaultBackend pods
    extraEnvs: []
    port: 8080
    ## Readiness and liveness probes for default backend
    ## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
    ##
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
  
  # Enable RBAC as per https://github.com/kubernetes/ingress-nginx/blob/main/docs/deploy/rbac.md and https://github.com/kubernetes/ingress-nginx/issues/266
  rbac:
    create: true
    scope: false
  serviceAccount:
    create: true
    name: ""
    automountServiceAccountToken: true
  