apiVersion: v2
name: prometheus
version: 0.1.0
description: A Helm chart for deploying Prometheus Stack
dependencies:
  - name: kube-prometheus-stack
    version: "75.15.1"
    repository: https://prometheus-community.github.io/helm-charts

