apiVersion: v2
name: sonarqube
version: 0.1.0
description: A Helm chart for deploying SonarQube
dependencies:
  - name: sonarqube
    version: "2025.6.1"
    repository: https://SonarSource.github.io/helm-chart-sonarqube

